train_file 文件夹已存在!
数据读取成功!
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\myproject\learn\trainer.py", line 175, in <module>
    start_train()
  File "C:\Users\Administrator\PycharmProjects\myproject\learn\trainer.py", line 172, in start_train
    total_timesteps = options.total_timesteps).train()
                                               ^^^^^^^
  File "C:\Users\Administrator\PycharmProjects\myproject\learn\trainer.py", line 81, in train
    env_train, env_trade = self.get_env(train_data, trade_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\PycharmProjects\myproject\learn\trainer.py", line 126, in get_env
    logger = configure(output_formats=["stdout", WandbOutputFormat()])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: configure() got an unexpected keyword argument 'output_formats'
